# Generated by Django 3.2.25 on 2024-07-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
