# Generated by Django 3.2.25 on 2024-07-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_userprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='charity_favs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
