# Generated by Django 3.2.25 on 2024-07-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_userprofile_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_consent',
            field=models.BooleanField(default=False),
        ),
    ]
