# Generated by Django 3.2.25 on 2024-06-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('charity_name', models.CharField(max_length=254)),
                ('charity_num', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=1800)),
                ('website_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('impact1', models.TextField(blank=True, max_length=254, null=True)),
                ('impact2', models.TextField(blank=True, max_length=254, null=True)),
                ('impact3', models.TextField(blank=True, max_length=254, null=True)),
                ('total_received_monthly', models.JSONField(blank=True)),
                ('total_received', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charities.category')),
            ],
        ),
    ]
