# Generated by Django 3.2.25 on 2024-06-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0002_alter_charity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='image_description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
