# Generated by Django 3.2.25 on 2024-06-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0003_charity_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='charity',
            name='impact1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charity',
            name='impact2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charity',
            name='impact3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
