# Generated by Django 3.2.25 on 2024-06-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0004_auto_20240626_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='total_received',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
