# Generated by Django 3.2.25 on 2024-07-16 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_number',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='stripe_pid',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='profiles.userprofile'),
        ),
    ]
