# Generated by Django 3.2.25 on 2024-07-22 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20240716_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with a "+" followed by 1 to 14 digits.', regex='^\\+\\d{1,14}$')]),
        ),
    ]
