# Generated by Django 3.2.25 on 2024-06-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charities', '0005_alter_charity_total_received'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('subscription', models.BooleanField(default=False)),
                ('donation_total', models.PositiveIntegerField(default=0)),
                ('donation_date', models.DateField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TargetCharity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_total', models.PositiveIntegerField(default=0)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_charities', to='charities.charity')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_charities', to='donations.donation')),
            ],
        ),
    ]
