# Generated by Django 3.2.25 on 2024-07-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='selected_charities',
            field=models.JSONField(default=list),
        ),
    ]
