# Generated by Django 3.2.25 on 2024-07-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_selected_charities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='subscription',
        ),
    ]
