# Generated by Django 3.2.25 on 2024-07-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sub_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
