# Generated by Django 3.2.25 on 2024-07-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_active',
            field=models.BooleanField(default=True),
        ),
    ]
