# Generated by Django 3.2.25 on 2024-07-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_donation_donation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(default='Not charged', max_length=12),
        ),
    ]
