# Generated by Django 3.2.25 on 2024-07-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_donation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donation_active',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='status',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_active',
            field=models.BooleanField(default=True),
        ),
    ]
