# Generated by Django 3.2.25 on 2024-07-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_auto_20240711_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_number',
            field=models.CharField(default=0, editable=False, max_length=32),
        ),
    ]
