# Generated by Django 3.2.25 on 2024-07-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_donation_donation_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
